### ISSUE TITLE
Use title case on blog post titles

### ISSUE THREAD

**Issue by pglevy** [Bixal/uswds-page-templates#40]

**Comment by bnaolu** [comment]
I noticed the H1 title on GH has the font-heading-3xl class. The Figma template is set on the H1 styling. Thoughts on this?

Other than that, I believe the post titles in Figma have been updated to H2 (GH page is looking good, too). Anything else I should take a look at before closing this, @pglevy?

**Comment by pglevy** [comment]
I think customizations of the text on web (using utility classes) are fine, even though it will differ from the Figma, which doesn't have the concept of "extending text styles" as far as I know.
